### PR TITLE
CLDCNTR-4202 Add multiple sessions support to Telegraf

### PR DESCRIPTION
**Pull request by ghost**
This PR adds the following changes to Telegraf:

1. Telegraf now is able to handle multiple orion-res sessions at the same time
2. Telegraf allows to configure per-session metrics filter. It will write only those metrics to the database that match the filter configured for the session.

---
This change is [Reviewable](https://reviewable.io/reviews/spirentorion/telegraf/28)

### CODE REVIEW

**Review by rmyers808 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/spirentorion/telegraf/28)* status: all files reviewed, 4 unresolved discussions (waiting on @aonnikov-spirent and @gkodama)

___
*[plugins/outputs/orionres/processor/processor.go, line 33 at r1](https://reviewable.io/reviews/spirentorion/telegraf/28#-MhR1cTAC7WIiiUiroYW:-MhR1cTAC7WIiiUiroYX:bi4ogge) ([raw file](https://github.com/spirentorion/telegraf/blob/35c78ec74da6729e203c703acc4ad46ac4dfa63e/plugins/outputs/orionres/processor/processor.go#L33)):*
> ```Go
> 	AddNewMetrics bool
> 	clients       map[string]*SessionClient
> 	sessionsTtl   int
> ```

Good idea to add TTL!
___
*[plugins/outputs/orionres/processor/processor.go, line 91 at r1](https://reviewable.io/reviews/spirentorion/telegraf/28#-MhQyrVD6xUEhkN5e64x:-MhQyrVD6xUEhkN5e64y:b-4cdxsw) ([raw file](https://github.com/spirentorion/telegraf/blob/35c78ec74da6729e203c703acc4ad46ac4dfa63e/plugins/outputs/orionres/processor/processor.go#L91)):*
> ```Go
> 	p.Lock()
> 	defer p.Unlock()
> 	return p.clients
> ```

I think returning clients map might lead to false sense of thread safety.  Maybe you should return a new map?
___
*[plugins/outputs/orionres/res/session/session.go, line 97 at r1](https://reviewable.io/reviews/spirentorion/telegraf/28#-MhR-g5d4SsNGtmT59T6:-MhR-g5d4SsNGtmT59T7:barpku6) ([raw file](https://github.com/spirentorion/telegraf/blob/35c78ec74da6729e203c703acc4ad46ac4dfa63e/plugins/outputs/orionres/res/session/session.go#L97)):*
> ```Go
> func (r *sessionResource) Delete(req *http.Request, id string) (int, interface{}) {
> 	clients := r.processor.Clients()
> 	_, ok := clients[id]
> ```

Is clients[id] thread safe?
___
*[plugins/outputs/orionres/res/session/session.go, line 116 at r1](https://reviewable.io/reviews/spirentorion/telegraf/28#-MhR-kIB3v5oJDkIWNLP:-MhR-kIB3v5oJDkIWNLQ:barpku6) ([raw file](https://github.com/spirentorion/telegraf/blob/35c78ec74da6729e203c703acc4ad46ac4dfa63e/plugins/outputs/orionres/res/session/session.go#L116)):*
> ```Go
> 	}
> 	clients := r.processor.Clients()
> 	c, ok := clients[id]
> ```

Is clients[id] thread safe?

**Review by gkodama — COMMENTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/spirentorion/telegraf/28)* status: all files reviewed, 7 unresolved discussions (waiting on @aonnikov-spirent)

___
*[plugins/outputs/orionres/processor/processor.go, line 118 at r1](https://reviewable.io/reviews/spirentorion/telegraf/28#-MhRAfDq79hyRodeyrds:-MhRAfDq79hyRodeyrdt:bkpqnyv) ([raw file](https://github.com/spirentorion/telegraf/blob/35c78ec74da6729e203c703acc4ad46ac4dfa63e/plugins/outputs/orionres/processor/processor.go#L118)):*
> ```Go
> 	now := time.Now()
> 	for _, sessionClient := range clients {
> 		// If client has no filters, is
> ```

nit: If client has no filters, is ... ?  (incomplete?)
___
*[plugins/outputs/orionres/res/filter/filter_test.go, line 53 at r1](https://reviewable.io/reviews/spirentorion/telegraf/28#-MhRBjF3DHdNCPwxFRJ1:-MhRBjF3DHdNCPwxFRJ2:bps1shi) ([raw file](https://github.com/spirentorion/telegraf/blob/35c78ec74da6729e203c703acc4ad46ac4dfa63e/plugins/outputs/orionres/res/filter/filter_test.go#L53)):*
> ```Go
> }
> 
> func TestFilerListSingleTagFilter(t *testing.T) {
> ```

nit: Filer -> Filter
(multiple occurrences)
___
*[plugins/outputs/orionres/res/filter/filter_test.go, line 105 at r1](https://reviewable.io/reviews/spirentorion/telegraf/28#-MhRC8k2Bwi41NuX41A6:-MhRC8k2Bwi41NuX41A7:b-owtv86) ([raw file](https://github.com/spirentorion/telegraf/blob/35c78ec74da6729e203c703acc4ad46ac4dfa63e/plugins/outputs/orionres/res/filter/filter_test.go#L105)):*
> ```Go
> }
> 
> func TestFilerListIncorrectValues(t *testing.T) {
> ```

nit: Might be better to rename IncorrectValues -> NonMatchingValue

**Review by ghost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirentorion/telegraf/28)* status: all files reviewed, 5 unresolved discussions (waiting on @aonnikov-spirent, @gkodama, and @rmyers808)

___
*[plugins/outputs/orionres/processor/processor.go, line 91 at r1](https://reviewable.io/reviews/spirentorion/telegraf/28#-MhQyrVD6xUEhkN5e64x:-MhSiLr06jhI27KpkCJ8:br50j16) ([raw file](https://github.com/spirentorion/telegraf/blob/35c78ec74da6729e203c703acc4ad46ac4dfa63e/plugins/outputs/orionres/processor/processor.go#L91)):*
<details><summary><i>Previously, rmyers808 (Richard Myers) wrote…</i></summary><blockquote>

I think returning clients map might lead to false sense of thread safety.  Maybe you should return a new map?
</blockquote></details>

Agree, let's return a copy of the map.
___
*[plugins/outputs/orionres/processor/processor.go, line 118 at r1](https://reviewable.io/reviews/spirentorion/telegraf/28#-MhRAfDq79hyRodeyrds:-MhSiMK_CIig6tsQ4qrD:bt2vr1b) ([raw file](https://github.com/spirentorion/telegraf/blob/35c78ec74da6729e203c703acc4ad46ac4dfa63e/plugins/outputs/orionres/processor/processor.go#L118)):*
<details><summary><i>Previously, gkodama wrote…</i></summary><blockquote>

nit: If client has no filters, is ... ?  (incomplete?)
</blockquote></details>

Fixed.
___
*[plugins/outputs/orionres/res/filter/filter_test.go, line 53 at r1](https://reviewable.io/reviews/spirentorion/telegraf/28#-MhRBjF3DHdNCPwxFRJ1:-MhShb1PAKuYLD45bJ4I:bb6un1j) ([raw file](https://github.com/spirentorion/telegraf/blob/35c78ec74da6729e203c703acc4ad46ac4dfa63e/plugins/outputs/orionres/res/filter/filter_test.go#L53)):*
<details><summary><i>Previously, gkodama wrote…</i></summary><blockquote>

nit: Filer -> Filter
(multiple occurrences)
</blockquote></details>

Done
___
*[plugins/outputs/orionres/res/filter/filter_test.go, line 105 at r1](https://reviewable.io/reviews/spirentorion/telegraf/28#-MhRC8k2Bwi41NuX41A6:-MhShlCcDkRwtkuuX0eu:bb6un1j) ([raw file](https://github.com/spirentorion/telegraf/blob/35c78ec74da6729e203c703acc4ad46ac4dfa63e/plugins/outputs/orionres/res/filter/filter_test.go#L105)):*
<details><summary><i>Previously, gkodama wrote…</i></summary><blockquote>

nit: Might be better to rename IncorrectValues -> NonMatchingValue
</blockquote></details>

Done
___
*[plugins/outputs/orionres/res/session/session.go, line 97 at r1](https://reviewable.io/reviews/spirentorion/telegraf/28#-MhR-g5d4SsNGtmT59T6:-MhSpiYL-OhbelHrhqs4:bmi3ang) ([raw file](https://github.com/spirentorion/telegraf/blob/35c78ec74da6729e203c703acc4ad46ac4dfa63e/plugins/outputs/orionres/res/session/session.go#L97)):*
<details><summary><i>Previously, rmyers808 (Richard Myers) wrote…</i></summary><blockquote>

Is clients[id] thread safe?
</blockquote></details>

Yes. See detailed reply below
___
*[plugins/outputs/orionres/res/session/session.go, line 116 at r1](https://reviewable.io/reviews/spirentorion/telegraf/28#-MhR-kIB3v5oJDkIWNLP:-MhSpDHm9UImCTUYsd97:bdiudgz) ([raw file](https://github.com/spirentorion/telegraf/blob/35c78ec74da6729e203c703acc4ad46ac4dfa63e/plugins/outputs/orionres/res/session/session.go#L116)):*
<details><summary><i>Previously, rmyers808 (Richard Myers) wrote…</i></summary><blockquote>

Is clients[id] thread safe?
</blockquote></details>

clients map is a copy here, no one else can modify it. All operations with the clients map in the `processor` are protected with mutex. So I think that it is thread safe.

**Review by rmyers808 — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/spirentorion/telegraf/28)* status: all files reviewed, 2 unresolved discussions (waiting on @aonnikov-spirent and @gkodama)

**Review by rmyers808 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/spirentorion/telegraf/28#-:-MhUc7Fj6pBhMlkvhb4g:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @aonnikov-spirent and @gkodama)

**Review by gkodama — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/spirentorion/telegraf/28#-:-MhWaLQEEPRMYdrnoNGr:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @aonnikov-spirent)

**Pull request merged**
